name: Continuous Deployment

# Only run when a commit is pushed to the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # deployment in our own server
    runs-on: self-hosted
  strategy:
    matrix:
      # discord.js recommends nodejs version 16.4.x or higher
      # 16.x will pull the latest image e.g, 16.6.x
      node-version: [16.x]

  steps:
      uses: actions/checkout@v2
    - name: using nodejs version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
      # install dependencies
    - run: npm install
      # run the bot while also declaring environment variables
    - run: TOKEN=${{ env.BOT_TOKEN }} CLIENTID=${{ env.BOT_CLIENT_ID }} GUILDID=${{ env.TESTING_GUILD_ID }} node .